### ISSUE TITLE
Can't include both linux/i2c.h and linux/i2c-dev.h if i2c-dev is provided by i2c-tools

### ISSUE THREAD

**Issue by thiagomacieira** [solettaproject/soletta#89] opened 2015-06-25 20:41 UTC
Whenever linux/i2c-dev.h is provided by i2c-tools, it is incompatible with linux/i2c.h.

Errors:
```
In file included from src/shared/sol-i2c-linux.c:39:0:
/usr/include/linux/i2c-dev.h:37:8: error: redefinition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from src/shared/sol-i2c-linux.c:38:0:
/usr/include/linux/i2c.h:68:8: note: originally defined here
 struct i2c_msg {
        ^
In file included from src/shared/sol-i2c-linux.c:39:0:
/usr/include/linux/i2c-dev.h:89:7: error: redefinition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
In file included from src/shared/sol-i2c-linux.c:38:0:
/usr/include/linux/i2c.h:128:7: note: originally defined here
 union i2c_smbus_data {
       ^
```

See https://build.opensuse.org/package/view_file/openSUSE:13.2/linux-glibc-devel/linux-glibc-devel.spec line 102

**Comment by glima** [comment] 2015-07-13 22:27
Since I'm starting vacations real soon and I could not reproduce it on time, @ceolin is going to chase the issue instead.

**Comment by thiagomacieira** [comment] 2015-07-13 22:34
Install OpenSUSE to reproduce. Or at the very least ensure that /usr/linux/linux/i2c-dev.h comes from the i2c-tools package and is unmodified from upstream.

This is most likely an OpenSUSE/i2c-tools bug. I'm asking for a workaround.

**Comment by ceolin** [comment] 2015-07-16 00:13
@thiagomacieira the following commit does the workaround. I've tested installing the header from i2c-tools manually and worked. Could you confirm it to me close this issue ?

https://github.com/solettaproject/soletta/commit/427f47fb2c7698d06438a243600d5c0c5aa5758d

**Comment by thiagomacieira** [comment] 2015-07-16 01:35
If you're getting that warning, I guess it fixes the issue, because I'm getting the warning too.

Why do you need to include linux/i2c.h? I didn't need to here.

**Comment by ceolin** [comment] 2015-07-16 15:06
linux/i2c-dev.h from i2c-tools contains the symbols from linux/i2c.h. But in the common case where i2c-dev.h comes from kernel it's necessary to include linux/i2c.h

**Comment by thiagomacieira** [comment] 2015-07-16 15:44
Understood.

**Closed** 2015-07-16 16:38 UTC
